import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import React from "react";
import {Toaster} from "react-hot-toast";

const LatoClass = Lato({
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html
            lang="en"
            className={`${LatoClass} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">
            <Toaster/>
            {children}
        </body>
        </html>
  );
}
